### ISSUE TITLE
[feature request] Versions on page

### ISSUE THREAD

**Issue by zurk** [bblfsh/dashboard#49]
Add the version of dashboard somewhere on the page.
Add the version of bblfsh-server with which dashboard should definitely work.

It would be really nice and useful for dashboard usage.

**Comment by eiso** [comment]
@marnovo this has my +1 as well. Could be as simple as just text in the footer.

**Comment by eiso** [comment]
@marnovo just doing a +1 on this one again since having dashboard,  server and driver versions on the dashboard, will make it a lot simpler to know what we're using. Especially when having multiple Babelfish servers running with different versions because of still some incompatibility on ML projects.

**Comment by bzz** [comment]
Before closing, let's make sure if we want to just show versions, or an error in case version missmatch.

**Comment by dpordomingo** [comment]
@bzz could you answer [your question](https://github.com/bblfsh/dashboard/issues/49#issuecomment-348475384)?

**Comment by bzz** [comment]
@dpordomingo I think it should be safe to close as version is shown now.

Validation of version parity would be handled in subsequent PRs.
